version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - log-ingestor-internal

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server=kafka:9092", "--list"]
      start_period: 15s
      interval: 10s
    networks:
      - log-ingestor-internal
    hostname: kafka

  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=connect-cluster
      - CONNECT_CONFIG_STORAGE_TOPIC=docker-connect-configs
      - CONNECT_OFFSET_STORAGE_TOPIC=docker-connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=docker-connect-status
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka
      - CONNECT_PLUGIN_PATH=/usr/share/java
    networks:
      - log-ingestor-internal

  producer:
    image: producer
    build:
      context: .
      dockerfile: 'Dockerfile.producer'
    ports:
      - '3000:3000'
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=logs
      - NUM_PARTITION=1
      - REPLICATION=1
    networks:
      - log-ingestor-internal
    hostname: producer

  consumer:
    image: consumer
    build:
      context: .
      dockerfile: 'Dockerfile.consumer'
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=logs
      - NUM_PARTITION=1
      - REPLICATION=1
      - PRODUCER=http://producer:3000
    networks:
      - log-ingestor-internal

networks:
  log-ingestor-internal: